export const env = {
  serverBaseUrl: process.env.REACT_APP_SERVER_BASE_URL,
  routes: {
    login: "/login",
    signup: "/signup",
    forgotpassword: "/forgotpassword",
    logout: "/logout",
    admin: "admin/",
    home: "/",
    addproduct: "/addproduct",
    categories: "/categories",
    myproducts: "/myproducts",
    productinfo: "/productinfo/:productid",
    allproducts: '/allproducts',
    userprofile: '/profile'
  },
  api: {
    login: "/auth/login",
    signup: "/auth/signup",
    forgotpassword: "/auth/forgotpassword",
    resetpassword: "/auth/resetpassword",
    profile: "/user/profile",
    pendingapprovals: "/admin/product/pendingapproval",
    approveproduct: "/admin/product/approveproduct",
    rejectproduct: "/admin/product/rejectproduct",
    categories: "/category",
    addcategory: "/category/add",
    editcategory: "/category/edit",
    addproduct: "/product/add",
    useruploadedproducts: "/product/userId",
    productdetailsbyid: "/product/details",
    productBids: "/bids/product",
    placenewbid: "/bids",
    allproducts: "/product",
    updateProfile: "/user/profile"
  },
};